const data = {
    products: [
        {
            _id: '1',
            name: 'Daft Punk',
            title: 'Random Access Memories',
            category: 'Electronic',
            image: '/assets/p1.jpeg',
            price: 310,
            nrStock: 10,
            brand: 'Columbia/Sony',
            rating: 3,
            nrRating: 25,
            description: 'Released 2013',
        },
        {
            _id: '2',
            name: 'Wu-Tang Clan',
            title: 'Enter the 36 Chambers',
            category: 'Hip Hop',
            image: '/assets/p2.jpeg',
            price: 110,
            nrStock: 15,
            brand: 'Independent',
            rating: 2.5,
            nrRating: 33,
            description: 'Released 1993',
        },
        {
            _id: '3',
            name: 'Guns n Roses',
            title: 'Appetite For Destruction',
            category: 'Rock',
            image: '/assets/p3.jpeg',
            price: 199,
            nrStock: 5,
            brand: 'Geffen',
            rating: 0.5,
            nrRating: 5,
            description: 'Released 1993',
        },
        {
            _id: '4',
            name: 'Pink Floyd',
            title: 'The Dark Side Of The Moon',
            category: 'Rock',
            image: '/assets/p4.jpeg',
            price: 150,
            nrStock: 5,
            brand: 'Capitol',
            rating: 4.6,
            nrRating: 7,
            description: 'Released 1973',
        },
        {
            _id: '5',
            name: 'Air',
            title: 'Moon Safari',
            category: 'Electronic',
            image: '/assets/p5.jpeg',
            price: 99,
            nrStock: 0,
            brand: 'Virgin',
            rating: 2.1,
            nrRating: 6,
            description: 'Released 1998',
        },
        {
            _id: '6',
            name: 'Company Flow',
            title: 'Funcrusher Plus',
            category: 'Hip Hop',
            image: '/assets/p6.jpeg',
            price: 299,
            nrStock: 0,
            brand: 'Rawkus',
            rating: 3.4,
            nrRating: 23,
            description: 'Released 1997',
        },
    ]
}

export default data