const data = {
    products: [
        {
            _id: '1',
            name: 'Round Lamp 1',
            category: 'Lamps',
            image: 'assets/p1.jpeg',
            price: 2599,
            brand: 'Gucci',
            rating: 5,
            numReviews: 10,
            description: 'a round lamp',
        },
        {
            _id: '2',
            name: 'Round Lamp 2',
            category: 'Lamps',
            image: 'assets/p2.jpeg',
            price: 399,
            brand: 'Sunny Drip',
            rating: 5,
            numReviews: 10,
            description: 'a round lamp',
        },
        {
            _id: '3',
            name: 'Round Lamp 3',
            category: 'Lamps',
            image: 'assets/p3.jpeg',
            price: 199,
            brand: 'BMW',
            rating: 5,
            numReviews: 10,
            description: 'a round lamp',
        },
        {
            _id: '4',
            name: 'Round Lamp 4',
            category: 'Lamps',
            image: 'assets/p4.jpeg',
            price: 1599,
            brand: 'Lights R Us',
            rating: 5,
            numReviews: 10,
            description: 'a round lamp',
        },
        {
            _id: '5',
            name: 'Round Lamp 5',
            category: 'Lamps',
            image: 'assets/p5.jpeg',
            price: 99,
            brand: 'BrightBall',
            rating: 5,
            numReviews: 10,
            description: 'a round lamp',
        },
        {
            _id: '6',
            name: 'Round Lamp 6',
            category: 'Lamps',
            image: 'assets/p6.jpeg',
            price: 299,
            brand: 'Lampville',
            rating: 5,
            numReviews: 10,
            description: 'a round lamp',
        },
    ]
}

export default data